name: 刷步数

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout codes
        uses: actions/checkout@v5

      - name: 初始化Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: 开始刷步数
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          pip3 install requests pytz pycryptodome
          python3 main.py
